# Generated by Django 4.2.11 on 2024-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('acc_name', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
    ]
