# Generated by Django 4.2.11 on 2024-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='em', max_length=35),
            preserve_default=False,
        ),
    ]
