# Generated by Django 4.2.11 on 2024-09-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('text_content', models.CharField(max_length=280)),
                ('image_content', models.CharField(max_length=35)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('engagements', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
