# Generated by Django 4.2.11 on 2024-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_notification_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
