# Generated by Django 4.2.11 on 2024-11-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from_notification_set', to='api.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_notification_set', to='api.user'),
        ),
    ]
