# Generated by Django 4.2.11 on 2024-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_convo_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user1_sent',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.CharField(default='', max_length=40),
        ),
    ]
