# Generated by Django 4.2.11 on 2024-11-20 03:53

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_usermessage_user1_sent_usermessage_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='')),
            ],
        ),
    ]
