# Generated by Django 4.2.11 on 2024-11-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='test_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='test_name',
            new_name='image_name',
        ),
    ]
