# Generated by Django 4.2.11 on 2024-11-21 00:06

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_test_image_rename_test_file_image_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
