# Generated by Django 4.2.11 on 2024-11-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='tweet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tweet'),
        ),
    ]
