# Generated by Django 4.2.11 on 2025-01-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usermessage_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.CharField(default='default-header-pic.jpg', max_length=100),
        ),
    ]
