# Generated by Django 4.2.11 on 2025-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_header_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.CharField(default='default-header-pic.png', max_length=100),
        ),
    ]
