# Generated by Django 5.0.2 on 2025-07-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_header_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
    ]
