# Generated by Django 5.0.2 on 2025-08-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_image_name_image_image_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_pics', to='api.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_pics', to='api.image'),
        ),
    ]
